[package]
name = "primitives"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://parity.io/"
license = "Unlicense"
publish = false
edition = "2021"

[dependencies]
sp-application-crypto = {  git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false  }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false }
sp-runtime = {  git = "https://github.com/paritytech/substrate.git", branch = "master", default-features = false  }

[features]
default = [ "std" ]
std = [
	"sp-application-crypto/std",
	"scale-info/std",
	"codec/std",
	"sp-core/std",
	"frame-system/std",
	"sp-runtime/std",
]
